name: phpDocumentor

on:
  push:
    branches: [master]

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - uses: actions/checkout@v4.2.1

      # Cambiar directorio de trabajo a la carpeta PHP
      - name: Cambiar a la carpeta PHP
        working-directory: ./PHP
        run: echo "Trabajando en la carpeta PHP"

      # Ejecutar phpDocumentor usando Docker
      - name: Generar documentaci贸n PHP
        working-directory: ./PHP
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d ./ -t ./docs

      # Commit y push de la documentaci贸n generada
      - name: Commit y push de la documentaci贸n
        working-directory: ./WebPhpEc2
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Actualizar documentaci贸n PHP" || echo "No hay cambios para commitear"
          git push
