name: deploy-destroy

on:
  workflow_dispatch: #! Permite ejecutar manualmente el flujo de trabajo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml
          tools: composer

      - name: Validar archivos de Composer
        run: |
          cd WebPhpEc2
          composer validate

      - name: Actualizar Composer
        run: |
          cd WebPhpEc2
          composer update

      - name: Darle permisos a PHPUnit
        run: chmod +x ./vendor/bin/phpunit

      - name: Ejecutar PHPUnit
        run: ./vendor/bin/phpunit tests
