name: deploy-destroy

on:
  workflow_dispatch: #! Permite ejecutar manualmente el flujo de trabajo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml
          tools: composer

      - name: Actualizar Composer
        run: |
          cd WebPhpEc2
          composer update

      - name: Darle permisos a PHPUnit
        run: |
          cd WebPhpEc2
          chmod +x ./vendor/bin/phpunit

      - name: Ejecutar PHPUnit
        id: phpunit-tests
        run: |
          cd WebPhpEc2
          ./vendor/bin/phpunit tests || exit 1

      - name: Verificar resultado de los tests
        if: success()
        run: echo "✅ Los tests pasaron correctamente."

      - name: Verificar fallos en los tests
        if: failure()
        run: echo "❌ Algunos tests fallaron."
