name: deploy-destroy

on:
  workflow_dispatch: #! Permite ejecutar manualmente el flujo de trabajo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: pasar mis tokens a aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Hacer el set up de tf
        uses: hashicorp/setup-terraform@v3

      - name: comprobar antes
        run: ls -la

      - name: inicializar terraform y planificar
        run: |
          cd Terraform
          ls -la  # Verifica los archivos en la carpeta Terraform
          terraform init
          terraform plan -no-color

      - name: apply terraform
        run: |
          cd Terraform
          terraform apply -auto-approve

      - name: Subir tfstate como artefacto
        uses: actions/upload-artifact@v4.4.3
        with:
          name: terraform-tfstate
          path: Terraform/terraform.tfstate

  destroy: #! Job para destruir la infraestructura
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Descargar tfstate como artefacto
        uses: actions/download-artifact@v4.1.8
        with:
          name: terraform-tfstate
          path: ./

      - name: pasar mis tokens a aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Hacer el set up de tf
        uses: hashicorp/setup-terraform@v3

      - name: inicializar terraform y destruir
        run: |
          cd Terraform
          terraform init
          terraform destroy -auto-approve #! Destruir la infraestructura automáticamente
